### ISSUE TITLE
UMDFastBindingWidgetClassExtension are not loaded for user widgets when running in standalone

### ISSUE THREAD

**Issue by jdaignault** [DoubleDeez/MDFastBinding#13]
Some context: We've upgraded our engine from Unreal 5.1 to 5.2, and along with that updated our MDFastBinding plugin to the latest commit.

We've recently been running into some issues when running in standalone, wherein bindings that were composed in the binding editor are not being manifested into field notify delegate subscriptions at runtime.

After some debugging, it appears that with commit `27b9dd593c1297ff99b43f96cf38bad7a2a2bbb8`, it's expected that `UMDFastBindingWidgetClassExtension` extensions should be serialized for user widget blueprint classes. Indeed, when running in editor mode it seems to preload and configure them just fine in `UMDFastBindingWidgetBlueprintExtension::HandleFinishCompilingClass`, but in standalone the list of extensions remains empty upon hitting `UUserWidget::NativeConstruct`.

Note that we did notice a lot of errors that read `uses a deprecated property-based MDFastBindingContainer, resave it to automatically upgrade it to a widget extension`. However, upon resaving the asset we then receive a lot of errors like such:

```
[2023.05.25-01.22.33:750][  0]LoadErrors: Warning: CreateExport: Failed to load Outer for resource 'MDFastBindingContainer_0': MDFastBindingWidgetBlueprintExtension /Game/UI/Common/Buttons/WBP_GenericButton.WBP_GenericButton:MDFastBindingWidgetBlueprintExtension_0
[2023.05.25-01.22.33:750][  0]LoadErrors: Warning: CreateExport: Failed to load Outer for resource 'MDFastBindingInstance_1': MDFastBindingContainer /Game/UI/Common/Buttons/WBP_GenericButton.WBP_GenericButton:MDFastBindingWidgetBlueprintExtension_0.MDFastBindingContainer_0
[2023.05.25-01.22.33:750][  0]LoadErrors: Warning: CreateExport: Failed to load Outer for resource 'MDFastBindingDestination_Function_0': MDFastBindingInstance /Game/UI/Common/Buttons/WBP_GenericButton.WBP_GenericButton:MDFastBindingWidgetBlueprintExtension_0.MDFastBindingContainer_0.MDFastBindingInstance_1
etc...
```

If you happen to have any advice on how to further investigate and/or resolve this, it would be much appreciated!

**Comment by jdaignault** [comment]
After more intense debugging, my suspicion here is that it's trying to load the extension `UMDFastBindingWidgetBlueprintExtension` (and consequently the package `MDFastBindingEditor`) while running in standalone, which would explain the errors listed above.

I compared this to what Epic is doing with `UMVVMWidgetBlueprintExtension_View`, and by contrast it appears that it exists within the module `ModelViewViewModelBlueprint` instead of `ModelViewViewModelEditor`, which struck me as an important difference.

On a hunch, I moved `UMDFastBindingWidgetBlueprintExtension` into the `MDFastBinding` module (and commented out stuff to make it compile). The following side effects were observed:

- Widgets containing bindings serialized with the 'old' method (CDO property) were upgraded safely
- Widgets containing bindings serialized with the 'new' method (before my fix) had their bindings deleted/unable to load (`Failed to load Outer` errors now occur in both Editor and Standalone contexts)
- After creating and serializing new bindings with my fix, those new bindings also worked while running in standalone, and no further warnings were exhibited for them

**Comment by DoubleDeez** [comment]
Hey @jdaignault, very nice find - I'm surprised that blueprints are recompiled when launching standalone, I was expecting standalone to use the serialized generated class extension.

I'll be pushing a change that splits the editor and blueprint/graph code into separate modules as you suggested and I'll also add redirectors so that existing bindings will continue to work.
