### ISSUE TITLE
Chaining a 'Call a Static Function' node to a 'Select Value' node orphans its connection

### ISSUE THREAD

**Issue by jdaignault** [DoubleDeez/MDFastBinding#14]
Some context: We've upgraded our engine from Unreal 5.1 to 5.2, and along with that updated our MDFastBinding plugin to the latest commit.

We have multiple bindings that followed a structure similar to **Custom FieldNotify Node -> Call a Static Function -> Select Value -> Destination Node**. After updating the plugin to the latest version, we noticed that the connection between **Call a Static Function -> Select Value** was broken. Even worse, when we tried re-plugging it in, it no longer seemed to trigger altogether.

After some debugging, I've noticed some finer details:

- Upon opening the binding editor on an affected widget, `SMDFastBindingEditorWidget::AssignBindingData` is executed
- It finds a BindingContainer serialized in the CDO, and invokes `MDFastBindingEditorHelpers::InitBindingContainerInBlueprint` from the first branch
- The following code executes: `UMDFastBindingContainer* Container = DuplicateObject(InitialContainer, FastBindingExtension);`
- This construction triggers `UMDFastBindingObject::PostLoad`, and travels down to `UMDFastBindingValue_Select::SetupBindingItems`
- The following code executes: `const FProperty* SelectValueProp = ResolveBindingItemProperty(MDFastBindingValue_Select_Private::SelectValueInputName);`
- **Something goes wrong here:** `SelectValueProp` evaluates to nullptr. Consequently, `ExpectedNames` only ends up populated with 1 value
- `OrphanBindingItem(It->Value);` triggers and (presumably) wipes out the binding item values eventually

Digging further, it seems that `SelectValueProp` was nullptr because `UMDFastBindingContainer::GetBindingOwnerClassDelegate` was left unbound. This only gets bound in `UMDFastBindingWidgetBlueprintExtension::BindContainerOwnerDelegate`, which takes place only after the object has finished being duplicated (and thus after the PostLoad, and after the bindings had become orphaned). `UMDFastBindingContainer::GetBindingOwnerClass` would then route to `UMDFastBindingWidgetBlueprintExtension` instead of its GeneratedClass type. This unfortunately breaks one of our custom FieldNotify nodes that was expecting a proper class type.

Interestingly, if the data is left alone in its 'pre-upgraded' state and is run in standalone (without having opened the binding editor prior), it works fine.

**Comment by jdaignault** [comment]
As an aside, it also seems that the member `UMDFastBindingObject::BindingOwnerClass` is no longer assigned to anywhere.

**Comment by jdaignault** [comment]
A bit more information: When running in standalone, the bindings seem to fail for a similar reason, in that `UMDFastBindingContainer::GetBindingOwnerClassDelegate` is left unbound during the PostLoad context. However, the fallback case ends up returning a `UMDFastBindingWidgetClassExtension` instead.

**Comment by DoubleDeez** [comment]
Hey @jdaignault I've submitted https://github.com/DoubleDeez/MDFastBinding/commit/c4e57ce5327970786b5c53c5338a831ed9e1eb27 as a potential fix to this.
I wasn't able to repro it but switching to the interface instead of delegate should mean that the BindingOwnerClass is always available and therefore PostLoad should work as expected.

Let me know/close this issue if that fixes your problem.
