### ISSUE TITLE
Installing Plugin

### ISSUE THREAD

**Issue by Babatunes805** [DoubleDeez/MDFastBinding#16]
The repo I downloaded does not work. When I put it into my project plugin folder it is not discovered. I deleted the 'main' from the folder with no success. I reconfigured the folder contents and ultimately it was discovered in Unreal but did not have any functionality. Any further guidance and insight would be greatly appreciated. I have included a photo of the folders I have so hopefully you can diagnose the issue I downloaded the repo as directed by the readme file but I'm a novice so I'm sure there is something I am misunderstanding. Please and Thank you!
![image](https://github.com/DoubleDeez/MDFastBinding/assets/112985597/00b1208c-c8fd-4def-a367-e7cfdb3ac125)

**Comment by Babatunes805** [comment]
I redownloaded the zip file and pasted the unzipped 'MDFastbinding-main' folder into my projects plugins folder but it will not compile. It seems like I had a download error the first time and this seems to have all of the correct files but I'm still unsuccessful. Thanks for responding so quickly!
![image](https://github.com/DoubleDeez/MDFastBinding/assets/112985597/50d78e98-21e6-4ae1-ba91-da3a1fd7cf21)
![image](https://github.com/DoubleDeez/MDFastBinding/assets/112985597/2372bfef-27fa-478b-b63a-66f982e45d61)
![image](https://github.com/DoubleDeez/MDFastBinding/assets/112985597/4605a25c-df53-4a37-bad4-98505daed1ed)

**Comment by DoubleDeez** [comment]
What's the full compile error? Looks like it's cutoff in the screenshot.
Also, what version of Unreal are you using?

**Comment by Babatunes805** [comment]
2>D:\Unreal\OlogunSurvival\Plugins\MDFastBinding\MDFastBinding-main\Source\MDFastBindingEditor\Public\Customizations\MDFastBindingPropertyBindingExtension.h(12): error C3668: 'FMDFastBindingPropertyBindingExtension::GetCurrentIcon': method with override specifier 'override' did not override any base class methods

**Comment by Babatunes805** [comment]
Do I have them nested appropriately? I've tried with an MDFastbinding folder then pasting the "MDFastbinding-main" with and without the -main and with it being the topmost folder in the plugins folder.

**Comment by DoubleDeez** [comment]
This is an issue with a new feature I added not being compatible with 5.1, I'll submit a fix shortly

**Comment by Babatunes805** [comment]
ok great thanks I appreciate that very much

**Comment by DoubleDeez** [comment]
Try grabbing latest, that should fix your issue - let me know if you run into other problems

**Comment by Babatunes805** [comment]
Thanks that did the trick! I'm still a little confused about implementation but the compile errors have been fixed and it is functioning. Is there any documentation in addition to the read me or is it a figure it out yourself situation. Either way I'm highly appreciative of you making this available as a resource.

**Comment by DoubleDeez** [comment]
Hey, yeah it's a bit light on the documentation. The [wiki](https://github.com/DoubleDeez/MDFastBinding/wiki) has some more detailed information on some specifics.

In the long term I'm planning to setup some more examples, but I'm a bit away from that still as I have a suite of UI plugins I'm working on and I want to document them working together.
