### ISSUE TITLE
Nodes don't save position after auto formatting with Blueprint Assist

### ISSUE THREAD

**Issue by DoubleDeez** [DoubleDeez/MDFastBinding#17]
Node position only saves after manually dragging the nodes

**Comment by jdaignault** [comment]
+1 on this issue, was about to write one up for this! I'll add some repro steps for context.

**Steps to reproduce:**

1. Create a widget and a binding
2. Create 2x `Read a Property` nodes, and position them such that they're vertically offset from each other
3. Connect the output of the first node to the path root of the second node
4. Select both nodes and press the keyboard shortcut to straighten their connections (typically `Q`)
5. Recompile the blueprint
6. Observe that both nodes return to their original positions
