### ISSUE TITLE
Function node parameters can be downcasted implicitly

### ISSUE THREAD

**Issue by jdaignault** [DoubleDeez/MDFastBinding#18]
Values provided as parameters to `Call a Function` and `Call a Static Function` nodes can be downcasted implicitly without any warnings or errors. This can lead to scenarios where a derived type that was upcasted to a base type can be sent into a function expecting a different derived type, leading to runtime issues.

**Steps to reproduce:**

1. Create a blueprint variable of type `UTexture` (Object Reference)
2. Create a blueprint function that accepts a `UTexture2D` parameter
3. Create a binding with a `Call a Function` destination node, and set it to the blueprint function that was just created
4. Add a `Read a Property` node, set its property path to the blueprint variable that was just created, and connect its output to the `Call a Function` parameter
5. Observe that it connects in the graph, and compiles without warning

![image](https://github.com/DoubleDeez/MDFastBinding/assets/1145663/41dce96f-ac31-4c7e-a5c1-1a5f9f03e5de)

**Comment by DoubleDeez** [comment]
This was done intentionally to support auto-casting containers (TArray/TSet/TMap) of UObjects so this is going to be a Won't Fix, but I will add checking for types that could _never_ work (eg. passing a Pawn to a Texture param)

**Comment by jdaignault** [comment]
I'm not sure I understand the reasoning, as downcasting a container of objects to would exhibit the same problems.

For context, we ran into an issue (multiple times) where a `UTexture2DDynamic` was upcasted to a `UTexture` in C++, only for that texture to be fed through a binding into a blueprint function that was expecting the parameter to be of type `UTexture2D`. This resulted in the blueprint function receiving an invalid object and created runtime issues. Due to the lack of warnings/errors, it took some time to troubleshoot where the problem actually occurred.

By contrast, the event graph does not allow for implicit downcasting either, the user needs to explicitly cast the type:

![image](https://github.com/DoubleDeez/MDFastBinding/assets/1145663/a37cef51-83f6-45b6-8deb-092c89eaac56)

At the very least, it feels like the binding should also require an explicit downcast with the `Cast Object` node before feeding that result into a function node (and that node could support casting containers of objects too):

![image](https://github.com/DoubleDeez/MDFastBinding/assets/1145663/8d49ac53-7d43-4b4f-9bd0-10f9fa9677d9)

**Comment by DoubleDeez** [comment]
If it was broken then it was fixed after your version, but the implicit casting is dynamic so the behaviour you mention of a `UTexture2DDynamic` getting passed to a `UTexture2D` param would not happen, the binding will check types in `FMDFastBindingPropertySetter_Objects` and pass nullptr if the types don't work. With my changes from yesterday, there's now design time checking for types that could _never_ work. Attached screenshots that show me passing a `APawn` to a `UTexture2D`, at runtime `SetBrushFromTexture` gets a nullptr.

![UnrealEditor_VWnMuWdbUt](https://github.com/DoubleDeez/MDFastBinding/assets/1893819/cbb42ed1-974c-4d0e-b885-2ba7db87cb04)
![UnrealEditor_IZGCtBRfvD](https://github.com/DoubleDeez/MDFastBinding/assets/1893819/f4aaa1f0-ba78-4da2-a541-508549701be2)

**Comment by jdaignault** [comment]
To add to this, C++ also doesn't allow for implicit downcasting, an explicit cast operator is required:

```
UTexture* Base = nullptr;
UTexture2D* Child = nullptr;

// upcast, ok
Base = Child;

// downcast, error C2440:
// Cast from base to derived requires dynamic_cast or static_cast
// '=': cannot convert from 'UTexture *' to 'UTexture2D *'
Child = Base;
```

**Comment by DoubleDeez** [comment]
> - The tech artist would have run into the error, and added a cast node to explicitly downcast the type (issue still occurs)
>   - If this happened, the programmer now has an extra hint in the bindings to help identify where things could have gone wrong

The fact that the issue would still happen in this scenario makes me believe that explicit casting isn't a foolproof solution to your problem. Sure, the cast node provides a hint but it's still easy to be blind to it since it's normal to cast objects.

I do think it would be valuable to markup wires that perform any sort of automatic casting (ie. pins that get set via a `IMDFastBindingPropertySetter`). Just need to figure out a clean unique visualization.

I find the streamlined workflow and saved CPU cycles too valuable to remove automatic casting for a problem that it doesn't 100% solve. I would accept a PR that adds a setting to disable it though.
