### ISSUE TITLE
Function nodes of type 'If Updates Needed' prevent Select Value nodes from refiring when a Field Notify is supplied as a parameter

### ISSUE THREAD

**Issue by jdaignault** [DoubleDeez/MDFastBinding#20]
Function nodes with the update type `If Updates Needed` appear to have the capability of short circuiting the execution of a `Select Value` node when chained together with another `Field Notify` node.

**Steps to reproduce:**

1. Create two FieldNotify blueprint variables, one as a bool and one as a float
2. Create a blueprint function that accepts a float parameter and prints the value to the screen
3. From `Event Construct` graph, script a small loop that continuously increments the float variable
4. Create a binding with a `Select Value` node
5. Create a `Field Notify` node for the boolean variable and feed it into the **Value** parameter
6. Create a `Field Notify` node for the float variable and feed it into the **False** parameter
7. Create a `Call a Function` destination node, which calls the newly created blueprint function and accepts the output of the `Select Value` node
8. Compile and run
9. Observe that the incrementing float value is repeatedly printed to the screen
10. Create a `Call a Static Function` node, having it call the function `OR Boolean` from `KismetMathLibrary`
11. Set the update type of the `Call a Static Function` node to `If Updates Needed`
12. Connect the `Field Notify` for the boolean to one of the inputs of the `Call a Static Function` node
13. Connect the output of the `Call a Static Function` node to the **Value** parameter of the `Select Value` node (and reconnect the `Field Notify` for the float to the **False** parameter if needed)
14. Compile and run
15. Observe that the float value is only printed once to the screen

**Workarounds:**

- Populate Select Value entries only with static data
- Use blueprint graph functions to perform the select logic
- Use the `Always` update type for the function node

![image](https://github.com/DoubleDeez/MDFastBinding/assets/1145663/d2e99f0d-c328-47c6-8fe3-cc55149432ad)
![image](https://github.com/DoubleDeez/MDFastBinding/assets/1145663/c164bc48-ee89-4c7e-94c9-a830ac3c90a9)

**Comment by DoubleDeez** [comment]
I wouldn't expect your setup to work at all since you're not broadcasting that `MyFloat` changed so the field notify will never trigger - which commit are you on?

**Comment by jdaignault** [comment]
I think we're still back at `511cf9c` from May 10th, but slated to (finally) get up to speed within the coming months.

Reading your comment and spotting this commit, this explains a few things...I imagine some assumptions we made might break once we integrate this lol: https://github.com/DoubleDeez/MDFastBinding/commit/37b9909c300ab1437474bdbee528237493c0460d

Is there a way to adjust the blueprint setup to broadcast the change to `MyFloat` once it has been updated? Regardless, if not, the issue still occurs if it was broadcasted from the C++ side (it's how we originally discovered the issue).

**Comment by DoubleDeez** [comment]
I believe UWidget has a built-in Broadcast Field function that works in BP pre-5.3.

Field notify support expanded in 5.3 to include all Blueprints that implement the FieldNotification interface and with that came an automatic broadcast when using the Set node on Field notify properties.

I think that commit (or a later one) will fix this issue as it included a full audit on how updates are triggered so I fixed a few issues there. I'll verify locally later.

**Comment by DoubleDeez** [comment]
Confirmed this works in latest (using Set w/ Broadcast instead of increment so the FieldNotify is triggered)

![UnrealEditor_52pvwxGQlR](https://github.com/DoubleDeez/MDFastBinding/assets/1893819/5cccaeb0-7c52-4148-87f4-a2de5f3c38ef)
