### ISSUE TITLE
Event graph breakpoints are hit while design time bindings are enabled

### ISSUE THREAD

**Issue by jdaignault** [DoubleDeez/MDFastBinding#24]
While design time bindings are enabled, there is a risk of the editor becoming unresponsive if a binding ends up calling a blueprint function that has a breakpoint set on it.

**Steps to reproduce:**

1. Create a new widget blueprint and open it
2. If not already enabled, click on **Enable Design-Time Bindings**
3. Create a blueprint function that accepts a `bool` parameter and prints the value to the screen
4. Place a breakpoint on the `Print String` node, and compile the blueprint
5. Create a binding with a `Call a Function` destination node, and set it to the blueprint function that was just created
6. Compile the blueprint, then click on the **Designer** button to return to the design view
7. Observe that the editor becomes mostly unresponsive, and that the following log is spammed:
```
Slate: Had to block on waiting for a draw buffer
```

![image](https://github.com/DoubleDeez/MDFastBinding/assets/1145663/eb7c6811-a121-42d0-a35b-b02a13557db6)

**Comment by DoubleDeez** [comment]
Does the same thing happen with breakpoints in PreConstruct?

**Comment by jdaignault** [comment]
It's similar-but-different. After setting up the breakpoint and hitting compile, the editor gets stuck with a 'saving asset' progress bar displayed:

![image](https://github.com/DoubleDeez/MDFastBinding/assets/1145663/a7e63a88-1c56-4728-9ea3-dafd19d1acfe)

And in the debugger output, the following is logged right at the end:

```
[2023.10.21-19.33.22:220][932]LogBlueprintDebug: Warning: Hit breakpoint on node 'CallFunc_PrintString', from offset 10
[2023.10.21-19.33.22:220][932]LogBlueprintDebug: 
Script call stack:
	Function /Game/Developers/Joel/IssueRepro.IssueRepro_C:PreConstruct
	Function /Game/Developers/Joel/IssueRepro.IssueRepro_C:ExecuteUbergraph_IssueRepro

[2023.10.21-19.33.22:223][932]LogSlate: Warning: Ignoring SetUserFocus because it's not an active modal Window (user 0 not set to SGraphPanel [SGraphEditorImpl.cpp(735)].
```

**Comment by DoubleDeez** [comment]
Doesn't look like Event Graph breakpoints from Bindings get hit at design time in 5.3 - PreConstruct breakpoints do, but can be stepped through without any issues.

As a workaround, you can disable design-time bindings in Editor Prefs to be able to get back into your BP to disable the breakpoint:

![image](https://github.com/DoubleDeez/MDFastBinding/assets/1893819/2aa7d6c5-551d-4b21-9c94-8ded3ab026cd)
