### ISSUE TITLE
Add support to detect binding modifications for the Blueprint Diff tool

### ISSUE THREAD

**Issue by jdaignault** [DoubleDeez/MDFastBinding#27]
The Blueprint Diff tool is handy for quickly identifying changes to blueprint variables and event graphs across revisions. However, changes made to bindings are not represented at all in the tool, requiring that all bindings need to be re-inspected for changes and spotting potential errors.

It would be incredibly useful if the Blueprint Diff tool had a way to display a comparison of changes made to bindings, perhaps in a manner similar to how it displays changes for the Event Graph.

**Comment by DoubleDeez** [comment]
See [this wiki page](https://github.com/DoubleDeez/MDFastBinding/wiki/Diffing-Binding-Graphs) on enabling diff support for bindings. Fortunately, Epic accepted my PR so this will be enabled by default in UE 5.4
