### ISSUE TITLE
Add fuzzy search support when searching for function and property path names

### ISSUE THREAD

**Issue by jdaignault** [DoubleDeez/MDFastBinding#28]
It can be difficult to remember the exact syntax for property names and functions, and having support for fuzzier search terms could be an ergonomic boon.

**Steps to reproduce:**

1. Create a binding and add a `Call a Function` node inside it
2. Click on the **Function** dropdown box, and type in “set vis”
3. Observe that the function `Set Visibility` appears as an option
4. Click on the **Function** dropdown box again, and type in “vis set”
5. Observe that the function `Set Visibility` no longer appears as an option

**Comment by DoubleDeez** [comment]
This is built-in to Unreal so that would require fixing in the engine itself.
