### ISSUE TITLE
Widget properties that are affected by a binding cannot be updated in the details panel

### ISSUE THREAD

**Issue by jdaignault** [DoubleDeez/MDFastBinding#52]
Whenever a binding is set up such that its destination will affect a widget property, that property will become greyed out and unmodifiable in the Designer Mode details panel.

**Steps to reproduce:**

1. Create a widget with a `RichTextBlock`
2. Create a binding with a `Read a Property` node for the `RichTextBlock`
3. Connect its output to a `Call a Function` destination node, and set its function to `Set Text`
4. Return to Designer Mode, and select the `RichTextBlock` in the widget hierarchy
5. Observe that in the details panel, the property `Text` is unmodifiable

This causes UX issues while trying to update the widget with 'default' data and visualize how it looks at design time. This issue occurs regardless of whether design time bindings are enabled.

![image](https://github.com/DoubleDeez/MDFastBinding/assets/1145663/5cea1276-8617-4edd-a9ab-ec5c3c6da6ca)

**Comment by DoubleDeez** [comment]
I'm not sure there's a way around this since that's built-in behavior

**Comment by DoubleDeez** [comment]
This is something that would need to be handled as an engine change:
![image](https://github.com/user-attachments/assets/fe8390a2-68d8-4817-bb65-96d21289c9d3)
